Upgrade to Gatsby 3
takeshape/takeshape-starter-shopify-gatsby pull request #2
Opened 2021-04-12 23:17 UTC by asprouse

# Documentation

You may freely merge markdown-only PRs but consider requesting review for anything substantial.

### Checklist:

-[ ] Include [ci skip] in the commit message

--------------------------------------------------------------------------------

# Bug Fix

### Screenshots

![Bug](https://www.takeshape.io/assets/images/homepage/content-editor.png)

### Test Plan (Steps to test):

1.  
1.  
1.  

### Checklist:

- [ ] Commit messages accurately document the changes made in this PR
- [ ] [Storybook](https://www.notion.so/takeshapeio/Storybook-Guide-07ece3c569c2422aafd4a023ab7065e3)
- [ ] [Write Test Plan](https://www.notion.so/takeshapeio/Test-Plan-Guide-714426ec991e4619be5e8ab5ad1a7db7)

--------------------------------------------------------------------------------

# Feature

### Screenshots

![Feature](https://www.takeshape.io/assets/images/homepage/content-editor.png)

### Test Plan (Steps to test):

1.  
1.  
1.  

### Checklist:

- [ ] Commit messages accurately document the changes made in this PR
- [ ] [Documentation](https://www.notion.so/takeshapeio/Documentation-Guide-d51f33c2a21948d4aaf34b342298afbf)
- [ ] [Tracking](https://www.notion.so/takeshapeio/Activity-Tracking-Guide-733957b032da4bbd8ea20e4ef3be660f)
- [ ] [Access Policy](https://www.notion.so/takeshapeio/Access-Policy-Guide-29b01eb689f04b8687b6d93f17061844)
- [ ] [Entitlements](https://www.notion.so/takeshapeio/Entitlement-Guide-2dfa36c6270941b98ee20d75c48bbb91)
- [ ] [Storybook](https://www.notion.so/takeshapeio/Storybook-Guide-07ece3c569c2422aafd4a023ab7065e3)
- [ ] [Write Test Plan](https://www.notion.so/takeshapeio/Test-Plan-Guide-714426ec991e4619be5e8ab5ad1a7db7)

2021-04-13 19:51 UTC, incompl requested changes
Test steps did not work. On fresh checkout when I do `npm run develop` I get this error:

`GraphQLError: Unknown type "TS_Product"`

2021-04-13 19:53 UTC, asprouse commented
> Test steps did not work. On fresh checkout when I do `npm run develop` I get this error:
> 
> `GraphQLError: Unknown type "TS_Product"`

Seems like you are missing the relevant `.env`. I will send this to you offline.

2021-04-13 20:31 UTC, incompl requested changes
Seems that product images are not working. I wonder if this would be fixed by moving to gatsby-plugin-image since gatsby-image is deprecated.

2021-05-26 16:54 UTC, incompl approved these changes

2021-05-26 21:18 UTC, merged